import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { HEADER_HEIGHT } from '@/constants'
import Header from './components/layout/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children, isHomePage}: {children: React.ReactNode, isHomePage: boolean}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header></Header>
        <div className='flex justify-center' style={{paddingTop: HEADER_HEIGHT+90}}>
          <div className='2xl:max-w-7xl xl:max-w-6xl lg:max-w-4xl md:max-w-2xl sm:max-w-xl'>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
