import type { IMenu } from "../_service/menu";

// NOTE:
// - 이 상수는 현재 프론트엔드에서만 사용되는 메뉴 정의입니다.
// - 백엔드 연동 전까지는 menuService.getMenuList / getMenu 가 이 상수를 그대로 사용합니다.
// - id / parentId 관계는 고정 값이므로, DB 시드 시에는 이 구조를 참고해서 생성하면 됩니다.

export const INITIAL_MENU_LIST: IMenu[] = [
  // ===== 상위 메뉴 =====
  {
    id: 1,
    parentId: null,
    title: "조재현 수학학원",
    link: "/",
    sort: 1,
    isActive: true,
    isShown: false,
    isExternal: false,
    isOpenInNewTab: false,
    permission: "anonymous",
    description: "메인 랜딩 페이지",
    createdAt: new Date("2025-01-01T00:00:00Z"),
    updatedAt: new Date("2025-01-01T00:00:00Z"),
  },
  {
    id: 2,
    parentId: null,
    title: "학원 소개",
    link: null, // 컨테이너 메뉴
    sort: 2,
    isActive: true,
    isShown: true,
    isExternal: false,
    isOpenInNewTab: false,
    permission: "anonymous",
    description: "학원 소개 관련 메뉴",
    createdAt: new Date("2025-01-01T00:00:00Z"),
    updatedAt: new Date("2025-01-01T00:00:00Z"),
  },
  {
    id: 3,
    parentId: null,
    title: "교과 수학",
    link: null,
    sort: 3,
    isActive: true,
    isShown: true,
    isExternal: false,
    isOpenInNewTab: false,
    permission: "anonymous",
    description: "초등/중등 수학 프로그램",
    createdAt: new Date("2025-01-01T00:00:00Z"),
    updatedAt: new Date("2025-01-01T00:00:00Z"),
  },
  {
    id: 4,
    parentId: null,
    title: "심화 수학",
    link: null,
    sort: 4,
    isActive: true,
    isShown: true,
    isExternal: false,
    isOpenInNewTab: false,
    permission: "anonymous",
    description: "시그마반, 요리수반 등 심화 과정",
    createdAt: new Date("2025-01-01T00:00:00Z"),
    updatedAt: new Date("2025-01-01T00:00:00Z"),
  },
  {
    id: 5,
    parentId: null,
    title: "게시판",
    link: "/board",
    sort: 5,
    isActive: true,
    isShown: false,
    isExternal: false,
    isOpenInNewTab: false,
    permission: "anonymous",
    description: "공지사항 및 게시판",
    createdAt: new Date("2025-01-01T00:00:00Z"),
    updatedAt: new Date("2025-01-01T00:00:00Z"),
  },
  {
    id: 6,
    parentId: null,
    title: "마이페이지",
    link: "/user/mypage",
    sort: 6,
    isActive: true,
    isShown: false,
    isExternal: false,
    isOpenInNewTab: false,
    permission: "user", // 로그인 유저
    description: "회원 전용 마이페이지",
    createdAt: new Date("2025-01-01T00:00:00Z"),
    updatedAt: new Date("2025-01-01T00:00:00Z"),
  },
  {
    id: 7,
    parentId: null,
    title: "관리자",
    link: "/admin",
    sort: 7,
    isActive: true,
    isShown: false, // 일반 노출 X
    isExternal: false,
    isOpenInNewTab: false,
    permission: "admin",
    description: "관리자 전용 페이지",
    createdAt: new Date("2025-01-01T00:00:00Z"),
    updatedAt: new Date("2025-01-01T00:00:00Z"),
  },

  // ===== 학원 소개 하위 메뉴 (parentId: 2) =====
  {
    id: 10,
    parentId: 2,
    title: "학원 소개",
    link: "/info/introduction",
    sort: 1,
    isActive: true,
    isShown: true,
    isExternal: false,
    isOpenInNewTab: false,
    permission: "anonymous",
    description: "학원 설립 취지 및 교육 철학",
    createdAt: new Date("2025-01-01T00:00:00Z"),
    updatedAt: new Date("2025-01-01T00:00:00Z"),
  },
  {
    id: 11,
    parentId: 2,
    title: "수업 안내",
    link: "/info/class",
    sort: 2,
    isActive: true,
    isShown: true,
    isExternal: false,
    isOpenInNewTab: false,
    permission: "anonymous",
    description: "수업 구성 및 커리큘럼 안내",
    createdAt: new Date("2025-01-01T00:00:00Z"),
    updatedAt: new Date("2025-01-01T00:00:00Z"),
  },
  {
    id: 12,
    parentId: 2,
    title: "오시는 길",
    link: "/info/location",
    sort: 3,
    isActive: true,
    isShown: true,
    isExternal: false,
    isOpenInNewTab: false,
    permission: "anonymous",
    description: "학원 위치 및 지도",
    createdAt: new Date("2025-01-01T00:00:00Z"),
    updatedAt: new Date("2025-01-01T00:00:00Z"),
  },

  // ===== 일반 수학 하위 메뉴 (parentId: 3) =====
  {
    id: 20,
    parentId: 3,
    title: "초등 교과 수학",
    link: "/common-math/elementary",
    sort: 1,
    isActive: true,
    isShown: true,
    isExternal: false,
    isOpenInNewTab: false,
    permission: "anonymous",
    description: "초등 과정 수학 프로그램",
    createdAt: new Date("2025-01-01T00:00:00Z"),
    updatedAt: new Date("2025-01-01T00:00:00Z"),
  },
  {
    id: 21,
    parentId: 3,
    title: "중등 교과 수학",
    link: "/common-math/middle",
    sort: 2,
    isActive: true,
    isShown: true,
    isExternal: false,
    isOpenInNewTab: false,
    permission: "anonymous",
    description: "중등 과정 수학 프로그램",
    createdAt: new Date("2025-01-01T00:00:00Z"),
    updatedAt: new Date("2025-01-01T00:00:00Z"),
  },

  // ===== 심화 수학 하위 메뉴 (parentId: 4) =====
  {
    id: 30,
    parentId: 4,
    title: "시그마 클래스",
    link: "/advanced-math/sigma-class",
    sort: 1,
    isActive: true,
    isShown: true,
    isExternal: false,
    isOpenInNewTab: false,
    permission: "anonymous",
    description: "심화 수학 시그마반 안내",
    createdAt: new Date("2025-01-01T00:00:00Z"),
    updatedAt: new Date("2025-01-01T00:00:00Z"),
  },
  {
    id: 31,
    parentId: 4,
    title: "요리수 연산 교실",
    link: "/advanced-math/yorisu",
    sort: 2,
    isActive: true,
    isShown: true,
    isExternal: false,
    isOpenInNewTab: false,
    permission: "anonymous",
    description: "심화 수학 요리수반 안내",
    createdAt: new Date("2025-01-01T00:00:00Z"),
    updatedAt: new Date("2025-01-01T00:00:00Z"),
  },

  // ===== 로그인/회원가입 (상위로 취급) =====
  {
    id: 40,
    parentId: null,
    title: "로그인",
    link: "/auth/login",
    sort: 8,
    isActive: true,
    isShown: false, // 헤더 우측 버튼 등으로 별도 처리 가능
    isExternal: false,
    isOpenInNewTab: false,
    permission: "anonymous",
    description: "로그인 페이지",
    createdAt: new Date("2025-01-01T00:00:00Z"),
    updatedAt: new Date("2025-01-01T00:00:00Z"),
  },
  {
    id: 41,
    parentId: null,
    title: "회원가입",
    link: "/auth/join/select-type",
    sort: 9,
    isActive: true,
    isShown: false,
    isExternal: false,
    isOpenInNewTab: false,
    permission: "anonymous",
    description: "회원가입 시작 페이지",
    createdAt: new Date("2025-01-01T00:00:00Z"),
    updatedAt: new Date("2025-01-01T00:00:00Z"),
  },

  // ===== 관리자 하위 메뉴 (parentId: 7) =====
  {
    id: 50,
    parentId: 7,
    title: "메뉴 관리",
    link: "/admin/menu",
    sort: 1,
    isActive: true,
    isShown: false,
    isExternal: false,
    isOpenInNewTab: false,
    permission: "admin",
    description: "사이트 메뉴 구조 관리",
    createdAt: new Date("2025-01-01T00:00:00Z"),
    updatedAt: new Date("2025-01-01T00:00:00Z"),
  },
];


