openapi: 3.0.0
info:
  title: Attachment API
  description: API for uploading and managing attachments
  version: 1.0.0

paths:
  /attachment-group/{id}:
    get:
      summary: "파일 그룹 기반 조회"
      description: "파일 그룹 기반 조회"
      tags:
        - AttachmentGroup
      parameters:
        - name: "id"
          in: "path"
          description: "파일 그룹 ID"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "파일 그룹 기반 조회"
          schema:
            type: "object"
            properties:
              attachments:
                type: "array"
                items:
                  type: "object"
                  properties:
                    id:
                      type: "integer"
                      format: "int64"
                    name:
                      type: "string"
                    url:
                      type: "string"
        404:
          description: "파일 그룹 또는 파일이 존재하지 않습니다."
          schema:
            type: "object"
            properties:
              error:
                type: "string"
        500:
          description: "서버 오류"
          schema:
            type: "object"
            properties:
              error:
                type: "string"