openapi: 3.0.0
info:
  title: Info API
  description: 정보 관련 API
  version: 1.0.0
paths:
  /info/programs:
    get:
      summary: 프로그램 정보 조회
      tags:
        - Info
      responses:
        '200':
          description: 프로그램 정보 조회 성공
  /info/tuition:
    get:
      summary: 수업료 조회
      tags:
        - Info
      responses:
        '200':
          description: 수업료 조회 성공