openapi: 3.0.0
info:
  title: Menu API
  description: 메뉴 관련 API
  version: 1.0.0
paths:
  /menu/list:
    get:
      summary: 메뉴 목록 조회
      tags:
        - Menu
      responses:
        '200':
          description: 메뉴 조회 성공
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Menu'
        '404':
          description: 메뉴 정보를 찾을 수 없음
  /menu/{id}:
    get:
      summary: 메뉴 조회
      tags:
        - Menu
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 메뉴 조회 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Menu'
        '404':
          description: 메뉴 정보를 찾을 수 없음
    put:
      summary: 메뉴 수정
      tags:
        - Menu
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Menu'
      responses:
        '200':
          description: 메뉴 수정 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Menu'
    delete:
      summary: 메뉴 삭제
      tags:
        - Menu
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 메뉴 삭제 성공
  /menu:
    post:
      summary: 메뉴 생성
      tags:
        - Menu
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Menu'
      responses:
        '201':
          description: 메뉴 생성 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Menu'

components:
  schemas:
    Menu:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        price:
          type: number
        description:
          type: string