openapi: 3.0.0
info:
  title: Menu API
  description: 메뉴 관련 API
  version: 1.0.0
paths:
  /menu/list:
    get:
      summary: 메뉴 조회
      tags:
        - Menu
      responses:
        '200':
          description: 메뉴 조회 성공